Repository kcp-dev/infra, pull requests merged in 2023-06, with the labels that each got.

#44 add qemu DaemonSet to allow multiarch Docker image building
  clusters/build/hack/ci/deploy.sh
  clusters/build/manifests/multiarch-deps-installer.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#45 add preset-ghcr-credentials Prow preset
  prow/config.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#47 add kcp-dev/edge-mc to Prow
  prow/config.yaml
  prow/jobs/edge-mc/edge-mc-presubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#46 Add post-kcp-publish-image job
  prow/jobs/kcp/kcp-postsubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#49 reduce build cluster size to save money
  clusters/build/manifests/machinedeployment-worker.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#50 🌱 Move builds for `ghcr.io/kcp-dev/infra/build` to prow
  .github/workflows/build-image.yaml
  images/build/env
  images/build/hack/build-image.sh
  prow/jobs/infra/infra-postsubmits.yaml
  prow/jobs/infra/infra-presubmits.yaml
Labels: dco-signoff: yes, lgtm, approved, size/L

#52 Prepare repository for handling multiple GitHub orgs in Prow
  clusters/prow/hack/lib.sh
  prow/jobs/kcp-dev/apiextensions-apiserver/apiextensions-apiserver-presubmits.yaml
  prow/jobs/kcp-dev/apimachinery/apimachinery-presubmits.yaml
  prow/jobs/kcp-dev/awesome-kcp/awesome-kcp-presubmits.yaml
  prow/jobs/kcp-dev/client-go/client-go-presubmits.yaml
  prow/jobs/kcp-dev/code-generator/code-generator-presubmits.yaml
  prow/jobs/kcp-dev/controller-runtime-example/controller-runtime-example-presubmits.yaml
  prow/jobs/kcp-dev/controller-runtime/controller-runtime-presubmits.yaml
  prow/jobs/kcp-dev/edge-mc/edge-mc-presubmits.yaml
  prow/jobs/kcp-dev/enhancements/enhancements-presubmits.yaml
  prow/jobs/kcp-dev/friends/friends-presubmits.yaml
  prow/jobs/kcp-dev/helm-charts/helm-charts-presubmits.yaml
  prow/jobs/kcp-dev/infra/infra-periodics.yaml
  prow/jobs/kcp-dev/infra/infra-postsubmits.yaml
  prow/jobs/kcp-dev/infra/infra-presubmits.yaml
  prow/jobs/kcp-dev/kcp-dev.github.io/kcp-dev.github.io-presubmits.yaml
  prow/jobs/kcp-dev/kcp.io/kcp.io-presubmits.yaml
  prow/jobs/kcp-dev/kcp/kcp-postsubmits.yaml
  prow/jobs/kcp-dev/kcp/kcp-presubmits.yaml
  prow/jobs/kcp-dev/logicalcluster/logicalcluster-presubmits.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#53 extend readme
  README.md
Labels: dco-signoff: yes, size/S, lgtm, approved

#51 🌱 Include kind and docker in build image
  images/build/Dockerfile
  images/build/README.md
  images/build/env
  images/build/hack/build-image.sh
  images/build/start-docker.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#55 migrate edge-mc to kubestellar
  README.md
  prow/config.yaml
  prow/jobs/kubestellar/kubestellar/kubestellar-presubmits.yaml
  prow/plugins.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#57 prow: enable transfer-issue plugin for kcp-dev org
  prow/plugins.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS
