Repository kcp-dev/infra, pull requests merged in 2023-05, with the labels that each got.

#4 Update Prow
  clusters/prow/hack/create-prow-configmaps.sh
  clusters/prow/hack/lib.sh
  clusters/prow/manifests/prow/01-cherrypicker.yaml
  clusters/prow/manifests/prow/01-crier.yaml
  clusters/prow/manifests/prow/01-deck-public.yaml
  clusters/prow/manifests/prow/01-deck.yaml
  clusters/prow/manifests/prow/01-gcsweb-public.yaml
  clusters/prow/manifests/prow/01-gcsweb.yaml
  clusters/prow/manifests/prow/01-ghproxy.yaml
  clusters/prow/manifests/prow/01-hook.yaml
  clusters/prow/manifests/prow/01-horologium.yaml
  clusters/prow/manifests/prow/01-needs-rebase.yaml
  clusters/prow/manifests/prow/01-prow-controller-manager.yaml
  clusters/prow/manifests/prow/01-sinker.yaml
  clusters/prow/manifests/prow/01-statusreconciler.yaml
  clusters/prow/manifests/prow/01-tide.yaml
  prow/config.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#5 add whitespace
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/XS

#9 Deploy Prow automatically
  clusters/build/hack/ci/deploy.sh
  clusters/prow/hack/ci/deploy.sh
  prow/config.yaml
  prow/jobs/infra/infra-postsubmits.yaml
  prow/jobs/infra/infra-presubmits.yaml
  prow/jobs/logicalcluster/logicalcluster-presubmits.yaml
  prow/plugins.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#10 Fix blob storage credentials
  clusters/prow/manifests/prow/01-crier.yaml
  clusters/prow/manifests/prow/01-deck-public.yaml
  clusters/prow/manifests/prow/01-deck.yaml
  clusters/prow/manifests/prow/01-gcsweb-public.yaml
  clusters/prow/manifests/prow/01-gcsweb.yaml
  clusters/prow/manifests/prow/01-tide.yaml
  prow/config.yaml
  prow/jobs/infra/infra-postsubmits.yaml
  prow/plugins.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#11 fix missing config_updater plugin for infra repo
  prow/plugins.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#13 run postsubmits only on the main branch
  prow/jobs/infra/infra-postsubmits.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#14 fix initial job-config ConfigMap not fitting config_updater
  clusters/prow/hack/lib.sh
Labels: dco-signoff: yes, lgtm, approved, size/XS

#12 fix context switching in deployment scripts
  clusters/build/hack/ci/deploy.sh
  clusters/prow/hack/ci/deploy.sh
  hack/lib.sh
Labels: dco-signoff: yes, size/M, lgtm, approved

#15 disable crier's slack integration for now
  clusters/prow/manifests/prow/01-crier.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#18 fix deck-public service
  clusters/prow/manifests/prow/01-deck-public.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#19 prow: add label_sync config and jobs
  prow/jobs/infra/infra-periodics.yaml
  prow/jobs/infra/infra-presubmits.yaml
  prow/labels.yaml
  prow/plugins.yaml
Labels: dco-signoff: yes, lgtm, approved, size/L, ok-to-test

#23 prow/jobs/infra: fix label-sync jobs
  prow/jobs/infra/infra-periodics.yaml
  prow/jobs/infra/infra-presubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved, ok-to-test

#24 Fix label-sync jobs
  prow/jobs/infra/infra-periodics.yaml
  prow/jobs/infra/infra-presubmits.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, ok-to-test

#20 prow/config: add branch protection by default to all repos
  prow/config.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved, ok-to-test

#22 Add template files
  CONTRIBUTING.md
  DCO
  README.md
  SECURITY.md
  code-of-conduct.md
Labels: dco-signoff: yes, lgtm, approved, size/L, needs-ok-to-test

#26 add all remaining kcp-dev repositories to prow
  prow/config.yaml
  prow/jobs/apiextensions-apiserver/apiextensions-apiserver-presubmits.yaml
  prow/jobs/apimachinery/apimachinery-presubmits.yaml
  prow/jobs/awesome-kcp/awesome-kcp-presubmits.yaml
  prow/jobs/client-go/client-go-presubmits.yaml
  prow/jobs/code-generator/code-generator-presubmits.yaml
  prow/jobs/controller-runtime-example/controller-runtime-example-presubmits.yaml
  prow/jobs/controller-runtime/controller-runtime-presubmits.yaml
  prow/jobs/enhancements/enhancements-presubmits.yaml
  prow/jobs/friends/friends-presubmits.yaml
  prow/jobs/helm-charts/helm-charts-presubmits.yaml
  prow/jobs/kcp-dev.github.io/kcp-dev.github.io-presubmits.yaml
  prow/jobs/kcp.io/kcp.io-presubmits.yaml
  prow/jobs/kcp/kcp-presubmits.yaml
Labels: dco-signoff: yes, lgtm, approved, size/L

#36 properly configure OAuth for Deck
  clusters/prow/manifests/prow/01-deck.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#37 🌱 use GitHub Actions to build an image usable for Prow jobs
  .github/workflows/build-image.yaml
  images/build/Dockerfile
Labels: dco-signoff: yes, size/M, lgtm, approved, ok-to-test

#38 🐛 correct format of build args passed to GitHub Actions
  .github/workflows/build-image.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, needs-ok-to-test
