Repository kcp-dev/infra, pull requests merged in 2025-01, with the labels that each got.

#80 Build PR images
  prow/jobs/kcp-dev/kcp/kcp-presubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#81 add buildah to build image
  images/build/Dockerfile
  images/build/env
Labels: dco-signoff: yes, lgtm, approved, size/XS

#82 separate kubectl and kindest versions in build image, update kind to 0.26.0
  images/build/Dockerfile
  images/build/env
  images/build/hack/build-image.sh
Labels: dco-signoff: yes, size/M, lgtm, approved

#83 add api-syncagent
  prow/config.yaml
  prow/jobs/kcp-dev/api-syncagent/api-syncagent-presubmits.yaml
  prow/plugins.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#84 add postsubmit for api-syncagent to produce container images
  prow/jobs/kcp-dev/api-syncagent/api-syncagent-postsubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#85 Add postsubmit job for kcp-operator to start building images
  prow/jobs/kcp-dev/kcp-operator/kcp-operator-postsubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#86 Update build image to Go 1.23.5
  images/build/README.md
  images/build/env
Labels: dco-signoff: yes, lgtm, approved, size/XS

#87 prow: enable gcsweb
  prow/config.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#88 Update gcsweb configuration to use s3 correctly
  clusters/prow/manifests/prow/01-gcsweb-public.yaml
  clusters/prow/manifests/prow/01-gcsweb.yaml
  prow/config.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#89 Upgrade MachineDeployments to Kubernetes 1.29.4
  clusters/prow/manifests/machinedeployment-stable.yaml
  clusters/prow/manifests/machinedeployment-worker.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS
