Repository kcp-dev/infra, pull requests merged in 2025-06, with the labels that each got.

#120 bump build image to Go 1.23.10, 1.24.4
  images/build/go-1.23/env
  images/build/go-1.24/env
Labels: dco-signoff: yes, lgtm, approved, size/XS

#123 Move iac folder into respective cluster folder and add athens deployment
  clusters/build/README.md
  clusters/build/hack/ci/deploy.sh
  clusters/build/hack/lib.sh
  clusters/build/hack/settings.sh
  clusters/build/manifests/athens.yaml
  clusters/build/manifests/cluster-autoscaler.yaml
  clusters/build/manifests/cluster-config.yaml
  clusters/build/manifests/machinedeployment-stable.yaml
  clusters/build/manifests/machinedeployment-worker.yaml
  clusters/build/manifests/multiarch-deps-installer.yaml
  clusters/build/opentofu/.env.example
  clusters/build/opentofu/.gitignore
  clusters/build/opentofu/.terraform.lock.hcl
  clusters/build/opentofu/Makefile
  clusters/build/opentofu/README.md
  clusters/build/opentofu/addons.tf
  clusters/build/opentofu/cluster.tf
  clusters/build/opentofu/network.tf
  clusters/build/opentofu/outputs.tf
  clusters/build/opentofu/provider.tf
  clusters/build/opentofu/terraform.tf
  clusters/build/opentofu/variables.tf
Labels: dco-signoff: yes, lgtm, approved, size/XL

#124 Add echodate to lib.sh
  clusters/build/hack/lib.sh
Labels: dco-signoff: yes, lgtm, approved, size/XS

#126 Add `actual_retry` to `lib.sh`
  clusters/build/hack/lib.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#127 deploy cgroup enabler to build cluster
  clusters/build/hack/ci/deploy.sh
  clusters/build/manifests/cgroups-v2-enabler.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved
